import 'dotenv/config'

export const env = {
  MONGODB_URI:process.env.MONGODB_URI,
  DATABASE_NAME:process.env.DATABASE_NAME,
  APP_HOST:process.env.APP_HOST,
  APP_PORT:process.env.APP_PORT,

  BUILD_MODE:process.env.BUILD_MODE,

  JWT_ACCESS_TOKEN: process.env.JWT_ACCESS_TOKEN,
  JWT_REFRESH_TOKEN: process.env.JWT_REFRESH_TOKEN,

  USERNAME_GMAIL: process.env.USERNAME_GMAIL,
  PASSWORD_GMAIL: process.env.PASSWORD_GMAIL,

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,

  CLIENT_URI: process.env.CLIENT_URI,
  VERIFY_ACCOUNT_TOKEN: process.env.VERIFY_ACCOUNT_TOKEN,

  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,

  SEVER_TELEPHONE_NUMBER: process.env.SEVER_TELEPHONE_NUMBER,

}
